name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.fork }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        env:
          NODE_ENV: production
          VITE_APP_VERSION: ${{ github.sha }}
          BASE_PATH: '/${{ github.event.repository.name }}/'
        run: npm run build

      - name: Add SPA fallback (404.html)
        run: cp dist/index.html dist/404.html

      - name: Disable Jekyll processing
        run: touch dist/.nojekyll

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    name: Deploy to Pages
    needs: build
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.fork }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
